filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
queue.mem:
  events: 4096

filebeat.modules:
- module: system

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "localhost:5601"
