version: "2.2"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    
    environment:
        - node.name=elasticsearch
        - node.master=true
        - cluster.initial_master_nodes=elasticsearch
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - discovery.zen.ping.unicast.hosts=elasticsearch
        - node.max_local_storage_nodes=4

        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200
        - 9300

    networks:
      - ${ELK_NET}
    depends_on:
      - logstash

  filebeat:
    build:
      context:  ./filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
        memlock:
          soft: -1
          hard: -1
    environment:      
           - ELASTICSEARCH_HOST=elasticsearch:9200    
           # disable strict permission checks    
    command: ["--strict.perms=false"]      
    volumes: 
        - filebeat_data:/usr/share/filebeat/data:rw
        - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
        - /var/run/docker.sock:/var/run/docker.sock
    ports: 
        - 5044:5044
    networks:
      - ${ELK_NET}
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION

    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - kibana:/usr/share/kibana/data
    ports: 
        - 5601:5601
    networks:
      - ${ELK_NET}
    depends_on: 
      - elasticsearch
    restart: unless-stopped

 
  logstash:
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION

    environment: 
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

    ports:
        - "5000:5000"
        - "9600:9600"
    networks:
      - ${ELK_NET}
    restart: unless-stopped

volumes: 
  esdata:
    driver: local
  kibana:
    driver: local
  logstash:
    driver: local
  filebeat_data:
    driver: local    
networks: 
  esnet:
    driver: bridge