version: '2'
services:
  
  logspout:  
    image: gliderlabs/logspout:v3
    restart: always
    command: 'udp://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000
    networks:
        - docker_elk
    depends_on:
        - logstash

  kibana:  
    image: kibana:5.6.5
    links:
      - 'elastic:elasticsearch'
    ports:
      - '5601:5601'
    networks:
        - docker_elk
    
  logstash:  
    image: logstash:5.6.5
    # command: 'logstash -e "input { tcp { port => 5000 } } output { elasticsearch { hosts => elastic } }"'
    command: 'logstash -e "input { udp { port  => 5000 codec => json } tcp { port  => 5000 codec => json } } filter { mutate { rename => {\"msg\" => \"message\"} } } output {	elasticsearch { hosts => elastic } stdout { codec => rubydebug } }"'
    # ports:
    #     - "5000"
    links:
      - elastic
    networks:
        - docker_elk

  elastic:  
    image: elasticsearch:5.6.5
    environment: 
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
        - docker_elk

  elastic2:  
    image: elasticsearch:5.6.5
    environment: 
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
        - docker_elk

  elastic3:  
    image: elasticsearch:5.6.5
    environment: 
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
        - docker_elk

  elastic4:  
    image: elasticsearch:5.6.5
    environment: 
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
        - docker_elk


networks:
  docker_elk:
    driver: bridge
