version: "2.2"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200
        - 9300
    expose:
        - 9200
    networks:
      - esnet
    restart: unless-stopped

volumes: 
  esdata:
    driver: local
networks: 
  esnet:
    driver: bridge