version: "2.2"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200
        - 9300
    expose:
        - 9200
    networks:
      - esnet
    depends_on:
      - logstash
    restart: unless-stopped


  filebeat:
    build:
      context:  ./filebeat
      args: 
        ELK_VERSION: $ELK_VERSION
    ulimits:
        memlock:
          soft: -1
          hard: -1
    environment:      
           - ELASTICSEARCH_HOST=elasticsearch:9200    
           # disable strict permission checks    
    command: ["--strict.perms=false"]      
    volumes: 
        - filebeat_data:/usr/share/filebeat/data:rw
        - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args: 
        ELK_VERSION: $ELK_VERSION

    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - kibana:/usr/share/kibana/data
    ports: 
        - 5601:5601
    networks:
      - esnet
    depends_on: 
      - elasticsearch
    restart: unless-stopped

 
  logstash:
    build:
      context: ./logstash
      args: 
        ELK_VERSION: $ELK_VERSION
    environment: 
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"


    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

    ports:
        - "5044"
        - "5000:5000"
        - "9600:9600"
    networks:
      - esnet
    restart: unless-stopped

volumes: 
  esdata:
    driver: local
  kibana:
    driver: local
  logstash:
    driver: local
  filebeat_data:
    driver: local    
networks: 
  esnet:
    driver: bridge