version: "2.2"
services:
  es01:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: es01
    environment: 
      - node.name=es01
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
  
  es02:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: es02
    environment: 
      - node.name=es02
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data

    networks:
      - esnet
  es03:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: es03
    environment: 
      - node.name=es03
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data

    networks:
      - esnet
  es04:
    build:
      context: ./elasticsearch
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: es04
    environment: 
      - node.name=es04
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true      
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
      - esdata04:/usr/share/elasticsearch/data

    networks:
      - esnet  

  logstash:
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION
    ulimits:
        memlock:
          soft: -1
          hard: -1
    environment: 
      - "LS_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:rw
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
        - 5000:5000
        - 9600:9600
    networks:
      - esnet
    restart: unless-stopped
  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
    environment: 
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - kibana:/usr/share/kibana/data
    ports: 
        - 5601:5601
    networks:
      - esnet
    restart: unless-stopped

  # # filebeat:
  # #   build:
  # #     context:  ./filebeat
  # #   ulimits:
  # #       memlock:
  # #         soft: -1
  # #         hard: -1
  # #   # environment:      
  # #   #        - ELASTICSEARCH_HOST=elasticsearch:9200    
  # #   #        # disable strict permission checks    
  # #   # command: ["--strict.perms=false"]      
  # #   volumes: 
  # #       - filebeat_data:/usr/share/filebeat/data:rw
  # #       - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
  # #       - /var/run/docker.sock:/var/run/docker.sock
  # #   networks:
  # #     - esnet
  # #   # depends_on:
  # #   #   - elasticsearch
  # #   restart: unless-stopped  

volumes: 
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  esdata04:
    driver: local
  kibana:
    driver: local
  # filebeat_data:
    # driver: local
networks: 
  esnet: