# xpack.license.self_generated.type: basic
# xpack.monitoring.enabled: true
# xpack.monitoring.elasticsearch.url: "http://elastic:9200"
# xpack.monitoring.elasticsearch.username: 
# xpack.monitoring.elasticsearch.password:
path.config: "/usr/share/logstash/pipeline"